create table recipes (
  id integer primary key generated by default as identity,
  recipe_name text not null,
  recipe_img text ,
  recipe_ingredients text not null,
  recipe_prep text not null,
  recipeType_id integer references recipeType(id) not null,
  tags text
);