create table recipe_user (
  id integer primary key generated by default as identity,
  user_name text not null unique,
  nickname text,
  password text not null
);

alter table ingredients
  add column
    user_id integer references recipe_user(id) on delete set null;